# Generated by Django 5.0.6 on 2024-05-10 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('embarcaciones', '0002_tipoembarcacion_alter_embarcacion_matricula_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('descripcion', models.CharField(max_length=250)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('embarcacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='embarcaciones.embarcacion')),
            ],
        ),
    ]
