# Generated by Django 5.0.6 on 2024-05-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0002_alter_publicacion_embarcacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='oculta',
            field=models.BooleanField(default=False),
        ),
    ]
