# Generated by Django 5.0.6 on 2024-06-24 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trueques', '0003_trueque_fecha_cierre_trueque_fecha_inicio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField()),
                ('contexto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trueques.trueque')),
                ('user_envio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puntuaciones_enviadas', to=settings.AUTH_USER_MODEL)),
                ('user_recibio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puntuaciones_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
