# Generated by Django 5.0.4 on 2024-05-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='año_fabricacion',
            field=models.DecimalField(decimal_places=0, default=2000, max_digits=4),
        ),
    ]
