# Generated by Django 5.0.4 on 2024-05-06 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Embarcacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('m_eslora', models.DecimalField(decimal_places=2, max_digits=5)),
                ('m_manga', models.DecimalField(decimal_places=2, max_digits=5)),
                ('m_calado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('motor', models.CharField(blank=True, max_length=100, null=True)),
                ('deuda', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.sede')),
            ],
        ),
    ]
