# Generated by Django 5.0.4 on 2024-05-08 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embarcaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEmbarcacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='embarcacion',
            name='matricula',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='embarcacion',
            name='motor',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ImagenEmbarcacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_especifico', models.CharField(max_length=100)),
                ('embarcacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='embarcaciones.embarcacion')),
            ],
        ),
        migrations.AlterField(
            model_name='embarcacion',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='embarcaciones.tipoembarcacion'),
        ),
    ]
