# Generated by Django 5.0.6 on 2024-05-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_empleconsede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sede',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
