# Generated by Django 5.0.6 on 2024-05-27 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('embarcaciones', '0002_tipoembarcacion_alter_embarcacion_matricula_and_more'),
        ('empleados', '0003_alter_sede_nombre'),
        ('vehiculos', '0002_alter_vehiculo_año_fabricacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trueque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('embarcacion1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trueques_como_embarcacion1', to='embarcaciones.embarcacion')),
                ('embarcacion2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trueques_como_embarcacion2', to='embarcaciones.embarcacion')),
                ('sede', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.sede')),
                ('usuario1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trueques_como_usuario1', to=settings.AUTH_USER_MODEL)),
                ('usuario2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trueques_como_usuario2', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehiculos.vehiculo')),
            ],
        ),
    ]
