# Generated by Django 5.0.4 on 2024-05-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueques', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trueque',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
    ]
