# Generated by Django 5.0.6 on 2024-06-02 23:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trueques', '0002_trueque_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='trueque',
            name='fecha_cierre',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='trueque',
            name='fecha_inicio',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
