# Generated by Django 5.0.4 on 2024-05-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0002_alter_oferta_embarcacion_ofertada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
    ]
