# Generated by Django 5.0.6 on 2024-07-03 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0004_oferta_oculta'),
        ('publicaciones', '0003_publicacion_oculta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='publicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='publicaciones.publicacion'),
        ),
    ]
